version: "3"

services:
  login-service:
    build: ./login-service
    ports:
      - "5001:5001"

  order-service:
    build: ./order-service
    ports:
      - "5002:5002"

  payment-service:
    build: ./payment-service
    ports:
      - "5003:5003"

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
    volumes:
      - grafana-data:/var/lib/grafana

volumes:
  grafana-data:      